<?php

use Illuminate\Database\Seeder;
use App\CategoryProduct;
class ProducHasCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CategoryProduct::insert([
            'id_product'=>17,
            'id_category'=>3
        ]);        
        CategoryProduct::insert([
            'id_product'=>10,
            'id_category'=>1
        ]);
        CategoryProduct::insert([
            'id_product'=>10,
            'id_category'=>5
        ]);
        CategoryProduct::insert([
            'id_product'=>12,
            'id_category'=>5
        ]);
        CategoryProduct::insert([
            'id_product'=>11,
            'id_category'=>5
        ]);
        CategoryProduct::insert([
            'id_product'=>8,
            'id_category'=>1
        ]);
        CategoryProduct::insert([
            'id_product'=>9,
            'id_category'=>1
        ]);
        CategoryProduct::insert([
            'id_product'=>13,
            'id_category'=>7
        ]);
        CategoryProduct::insert([
            'id_product'=>11,
            'id_category'=>5
        ]);
        CategoryProduct::insert([
            'id_product'=>7,
            'id_category'=>2
        ]);
        CategoryProduct::insert([
            'id_product'=>13,
            'id_category'=>6
        ]);
        CategoryProduct::insert([
            'id_product'=>14,
            'id_category'=>7
        ]);
        CategoryProduct::insert([
            'id_product'=>15,
            'id_category'=>7
        ]);
        CategoryProduct::insert([
            'id_product'=>15,
            'id_category'=>3
        ]);
        CategoryProduct::insert([
            'id_product'=>16,
            'id_category'=>3
        ]);
        CategoryProduct::insert([
            'id_product'=>18,
            'id_category'=>3
        ]);
        CategoryProduct::insert([
            'id_product'=>2,
            'id_category'=>4
        ]);
        CategoryProduct::insert([
            'id_product'=>3,
            'id_category'=>4
        ]);
        CategoryProduct::insert([
            'id_product'=>4,
            'id_category'=>9
        ]);
        CategoryProduct::insert([
            'id_product'=>5,
            'id_category'=>10
        ]);
        CategoryProduct::insert([
            'id_product'=>1,
            'id_category'=>8
        ]);
        CategoryProduct::insert([
            'id_product'=>6,
            'id_category'=>11
        ]);
    }
}
